apiVersion: v2
name: sample-app
description: Sample application for GitOps demo
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - sample
  - webapp
  - gitops
  - demo
maintainers:
  - name: incoquinita
    email: incoquinita@example.com
